services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: url-shortener
        container_name: url-shortener-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./laravel:/var/www
        networks:
            - url-shortener

    nginx:
        image: nginx:alpine
        container_name: url-shortener-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./laravel:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - url-shortener

    pgsql:
        image: postgres:15
        container_name: url-shortener-pgsql
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - url-shortener

networks:
    url-shortener:
        driver: bridge 